# Generated by Django 4.2.3 on 2025-08-29 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_doaatype_alter_doaa_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasbih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasbih_count', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tasbih', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
